name: KokuminTeamPvP
main: me.nucha.teampvp.TeamPvP
version: 2.0
softdepend: [LunaChat, KokuminServer, KokuminCore]
commands:
  stats:
  maps:
    aliases: [rotation, rot]
  gamestart:
    permission: kokuminteampvp.start
  gameend:
    permission: kokuminteampvp.end
  cancelstart:
    permission: kokuminteampvp.cancelstart
  cancelcycle:
    permission: kokuminteampvp.cancelcycle
  cycle:
    permission: kokuminteampvp.cycle
  skipthismap:
    permission: kokuminteampvp.skipthismap
  setnext:
    permission: kokuminteampvp.setnext
  gameadmin:
    permission: kokuminteampvp.gameadmin
    aliases: [ga]
  match:
  staff:
    permission: kokuminteampvp.staff
    aliases: [mod]